name: GitHub Actions Demo
on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6 # setup the repo

      - uses: actions/setup-python@v6 # setup python
        with: 
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: PYTHONPATH=. pytest pytest
